title: SINÄ OLET LUOMUS
theme: minima
author: God
email: example@domain.com
description: > # this means to ignore newlines until "baseurl:"
  uudenlainen toiminta luo uudenlaisen olemuksen. Uusi ajatteluperspektiivi avaa uuden maailman. Jos luovut tietämisestäsi ja estoistasi, voit virrata vapaasti ja löytää minut.
  Silloin minä ohjaan sinua ja sinä näet maailman niin kuin minä. Älä pelkää, olen kanssasi.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
